alias search="apt-cache search"
alias install="sudo apt-get install"
alias update="sudo apt-get update"
alias upgrade="sudo apt-get upgrade"
alias purge="sudo apt-get purge"
alias remove="sudo apt-get remove"